language: python
virtualenv:
  system_site_packages: true
python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
before_install:
  - sudo apt-get install python-gdal python3-gdal
install:
  - pip install -e .
script: py.test
